Name	About	Labels	Assignees
Bug Report	You think something is broken in Fooocus	bug,triage	
The title of the bug report should be short and descriptive.
Use relevant keywords for searchability.
Do not leave it blank, but also do not put an entire error log in it.


Checklist
Please perform basic debugging to see if your configuration is the cause of the issue.
Basic debug procedure
　1. Update Fooocus - sometimes things just need to be updated
　2. Backup and remove your config.txt - check if the issue is caused by bad configuration
　3. Try a fresh installation of Fooocus in a different directory - see if a clean installation solves the issue
Before making a issue report please, check that the issue hasn't been reported recently.


The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)

The issue exists on a clean installation of Fooocus

The issue exists in the current version of Fooocus

The issue has not been reported before recently

The issue has been reported before but has not been fixed yet
Please fill this form with as much information as possible. Don't forget to add information about "What browsers" and provide screenshots if possible

What happened?
*
image generation is not working as intended.
Tell us what happened in a very clear and simple way

Steps to reproduce the problem
*
1. Go to ...
2. Press ...
3. ...
Please provide us with precise step by step instructions on how to reproduce the bug

What should have happened?
*
Fooocus should ...
Tell us what you think the normal behavior should be

What browsers do you use to access Fooocus?
Where are you running Fooocus?
What operating system are you using?
Windows 10
Console logs
*
Please provide full cmd/terminal logs from the moment you started UI to the end of it, after the bug occured. If it's very long, provide a link to pastebin or similar service.

Additional information
Please provide us with any relevant additional info or context.
Examples:
