Name	About	Labels	Assignees
Feature request	Suggest an idea for this project	enhancement,triage	

Is there an existing issue for this?
Please search to see if an issue already exists for the feature you want, and that it's not implemented in a recent build/commit.


I have searched the existing issues and checked the recent builds/commits
*
Please fill this form with as much information as possible, provide screenshots and/or illustrations of the feature if possible

What would your feature do?
*
Tell us about your feature in a very clear and simple way, and what problem it would solve

Proposed workflow
*
1. Go to .... 
2. Press ....
3. ...

Please provide us with step by step information on how you'd like the feature to be accessed and used

Additional information
Add any other context or screenshots about the feature request here.
